<acquisitions>
  <acquisition>
    <global_id>
      20160823143323-578026
    </global_id>
    <name>
      ref-cpx-klb1
    </name>
    <device/>
    <technique/>
    <operator/>
    <sample_global_id>
      20090223093040.hkitagawa
    </sample_global_id>
    <sample_name>
      ref-cpx-klb1
    </sample_name>
    <description/>
    <chemistries>
      <analysis>
        <nickname>
          Lu
        </nickname>
        <value>
          0.3
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Yb
        </nickname>
        <value>
          2.12
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Er
        </nickname>
        <value>
          2.23
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Y
        </nickname>
        <value>
          23.7
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Li
        </nickname>
        <value>
          1.37
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Dy
        </nickname>
        <value>
          3.67
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Tb
        </nickname>
        <value>
          0.524
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Gd
        </nickname>
        <value>
          2.59
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Eu
        </nickname>
        <value>
          0.707
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Hf
        </nickname>
        <value>
          0.993
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Zr
        </nickname>
        <value>
          28.81
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Sm
        </nickname>
        <value>
          1.72
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Sr
        </nickname>
        <value>
          36.06
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Pr
        </nickname>
        <value>
          0.487
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Ce
        </nickname>
        <value>
          1.76
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          La
        </nickname>
        <value>
          0.229
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          B
        </nickname>
        <value>
          0.042
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Nb
        </nickname>
        <value>
          0.011
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Ba
        </nickname>
        <value>
          0.18
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          NiO
        </nickname>
        <value>
          0.057285714
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          K2O
        </nickname>
        <value>
          0.0205
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Na2O
        </nickname>
        <value>
          1.76
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.07
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          MgO
        </nickname>
        <value>
          14.87
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.34
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          MnO
        </nickname>
        <value>
          0.11
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.03
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          FeO
        </nickname>
        <value>
          3.08
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.16
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Cr2O3
        </nickname>
        <value>
          0.78
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.05
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Al2O3
        </nickname>
        <value>
          7.28
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.12
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          TiO2
        </nickname>
        <value>
          0.54
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.03
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Cl
        </nickname>
        <value>
          0.00625
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          CaO
        </nickname>
        <value>
          19.38
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.26
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          SiO2
        </nickname>
        <value>
          51.95
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.14
        </uncertainty>
        <label/>
        <info/>
      </analysis>
    </chemistries>
  </acquisition>
  <acquisition>
    <global_id>
      20160823143340-619547
    </global_id>
    <name>
      ref-cpx-sax33
    </name>
    <device/>
    <technique/>
    <operator/>
    <sample_global_id>
      20090205120518.hkitagawa
    </sample_global_id>
    <sample_name>
      cpx-sax33
    </sample_name>
    <description/>
    <chemistries>
      <analysis>
        <nickname>
          Be
        </nickname>
        <value>
          0.5217
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Tm
        </nickname>
        <value>
          0.05887
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Ho
        </nickname>
        <value>
          0.274
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Nd
        </nickname>
        <value>
          5.377
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Pb
        </nickname>
        <value>
          0.09643
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Ta
        </nickname>
        <value>
          0.072
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          U
        </nickname>
        <value>
          0.009437
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Th
        </nickname>
        <value>
          0.0143
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Lu
        </nickname>
        <value>
          0.03733
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Yb
        </nickname>
        <value>
          0.298
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Er
        </nickname>
        <value>
          0.561
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Y
        </nickname>
        <value>
          5.52
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Li
        </nickname>
        <value>
          3.91
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Dy
        </nickname>
        <value>
          1.697
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Tb
        </nickname>
        <value>
          0.3173
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Gd
        </nickname>
        <value>
          2.147
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Eu
        </nickname>
        <value>
          0.673
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Hf
        </nickname>
        <value>
          6.4
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Zr
        </nickname>
        <value>
          117.0
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Sm
        </nickname>
        <value>
          1.883
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Sr
        </nickname>
        <value>
          88.0
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Pr
        </nickname>
        <value>
          0.8503
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Ce
        </nickname>
        <value>
          4.28
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          La
        </nickname>
        <value>
          0.9596
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          B
        </nickname>
        <value>
          0.358
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Nb
        </nickname>
        <value>
          0.3485
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Ba
        </nickname>
        <value>
          0.0692
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          NiO
        </nickname>
        <value>
          0.0465
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          K2O
        </nickname>
        <value>
          0.0225
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Na2O
        </nickname>
        <value>
          3.74
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.14
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          MgO
        </nickname>
        <value>
          12.54
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.18
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          MnO
        </nickname>
        <value>
          0.15
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.02
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          FeO
        </nickname>
        <value>
          8.66
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.33
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Cr2O3
        </nickname>
        <value>
          0.0188
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Al2O3
        </nickname>
        <value>
          5.62
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.09
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          TiO2
        </nickname>
        <value>
          1.01
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.05
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Cl
        </nickname>
        <value>
          0.00517
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          CaO
        </nickname>
        <value>
          14.48
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.15
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          SiO2
        </nickname>
        <value>
          53.59
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.19
        </uncertainty>
        <label/>
        <info/>
      </analysis>
    </chemistries>
  </acquisition>
  <acquisition>
    <global_id>
      20160823143349-018509
    </global_id>
    <name>
      ref-cpx-sax39c
    </name>
    <device/>
    <technique/>
    <operator/>
    <sample_global_id>
      20090220110831.hkitagawa
    </sample_global_id>
    <sample_name>
      cpx-sax39c
    </sample_name>
    <description/>
    <chemistries>
      <analysis>
        <nickname>
          d7Li
        </nickname>
        <value>
          3.47
        </value>
        <unit>
          permil
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Tm
        </nickname>
        <value>
          0.061555636
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Ho
        </nickname>
        <value>
          0.244439997
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Nd
        </nickname>
        <value>
          4.5624654
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Pb
        </nickname>
        <value>
          0.043521117
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Ta
        </nickname>
        <value>
          0.0207
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          U
        </nickname>
        <value>
          0.004652296
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Th
        </nickname>
        <value>
          0.0143584
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Rb
        </nickname>
        <value>
          0.00555633
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Cs
        </nickname>
        <value>
          0.000762122
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Lu
        </nickname>
        <value>
          0.036320825
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Yb
        </nickname>
        <value>
          0.316753906
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Er
        </nickname>
        <value>
          0.526737869
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Y
        </nickname>
        <value>
          6.442154293
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Li
        </nickname>
        <value>
          3.052649172
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Dy
        </nickname>
        <value>
          1.473384627
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Tb
        </nickname>
        <value>
          0.269126823
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Gd
        </nickname>
        <value>
          1.722796122
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Eu
        </nickname>
        <value>
          0.547721744
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Hf
        </nickname>
        <value>
          1.05
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Zr
        </nickname>
        <value>
          19.3
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Sm
        </nickname>
        <value>
          1.652663
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Sr
        </nickname>
        <value>
          73.724079
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Pr
        </nickname>
        <value>
          0.687965
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Ce
        </nickname>
        <value>
          3.478434336
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          La
        </nickname>
        <value>
          0.873668424
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          B
        </nickname>
        <value>
          0.543365666
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Nb
        </nickname>
        <value>
          0.148
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Ba
        </nickname>
        <value>
          0.234790983
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          NiO
        </nickname>
        <value>
          0.050285714
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          K2O
        </nickname>
        <value>
          0.01
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Na2O
        </nickname>
        <value>
          2.13
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.11
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          MgO
        </nickname>
        <value>
          16.97
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.16
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          MnO
        </nickname>
        <value>
          0.13
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.01
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          FeO
        </nickname>
        <value>
          6.5
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.2
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Cr2O3
        </nickname>
        <value>
          0.1
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.01
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Al2O3
        </nickname>
        <value>
          5.69
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.11
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          TiO2
        </nickname>
        <value>
          0.72
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.04
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Cl
        </nickname>
        <value>
          0.005
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          CaO
        </nickname>
        <value>
          13.91
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.22
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          SiO2
        </nickname>
        <value>
          53.41
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.21
        </uncertainty>
        <label/>
        <info/>
      </analysis>
    </chemistries>
  </acquisition>
  <acquisition>
    <global_id>
      20170117151118-683875
    </global_id>
    <name>
      ref_gl_bhvo2
    </name>
    <device/>
    <technique/>
    <operator/>
    <sample_global_id>
      20131126113124-608483
    </sample_global_id>
    <sample_name>
      ref-glass-USGS-BHVO02G
    </sample_name>
    <description/>
    <chemistries>
      <analysis>
        <nickname>
          P2O5
        </nickname>
        <value>
          0.27
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.02
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          K2O
        </nickname>
        <value>
          0.52
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.01
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Na2O
        </nickname>
        <value>
          2.22
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.08
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          CaO
        </nickname>
        <value>
          11.4
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.2
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          MgO
        </nickname>
        <value>
          7.23
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.12
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Fe2O3T
        </nickname>
        <value>
          12.3
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.2
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Al2O3
        </nickname>
        <value>
          13.5
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.2
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          TiO2
        </nickname>
        <value>
          2.73
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.04
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          SiO2
        </nickname>
        <value>
          49.9
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.6
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Th
        </nickname>
        <value>
          1.2
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty>
          0.3
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Ta
        </nickname>
        <value>
          1.4
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Hf
        </nickname>
        <value>
          4.1
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty>
          0.3
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Lu
        </nickname>
        <value>
          0.28
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty>
          0.01
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Yb
        </nickname>
        <value>
          2.0
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty>
          0.2
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Ho
        </nickname>
        <value>
          1.04
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty>
          0.04
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Tb
        </nickname>
        <value>
          0.9
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Gd
        </nickname>
        <value>
          6.3
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty>
          0.2
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Sm
        </nickname>
        <value>
          6.2
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty>
          0.4
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Nd
        </nickname>
        <value>
          25.0
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty>
          1.8
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Ce
        </nickname>
        <value>
          38.0
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty>
          2.0
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          La
        </nickname>
        <value>
          15.0
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty>
          1.0
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Ba
        </nickname>
        <value>
          130.0
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty>
          13.0
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Sn
        </nickname>
        <value>
          1.9
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Nb
        </nickname>
        <value>
          18.0
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty>
          2.0
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Zr
        </nickname>
        <value>
          172.0
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty>
          11.0
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Y
        </nickname>
        <value>
          26.0
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty>
          2.0
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Sr
        </nickname>
        <value>
          389.0
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty>
          23.0
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Rb
        </nickname>
        <value>
          9.8
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty>
          1.0
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Ga
        </nickname>
        <value>
          21.7
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty>
          0.9
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Zn
        </nickname>
        <value>
          103.0
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty>
          6.0
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Cu
        </nickname>
        <value>
          127.0
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty>
          7.0
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Ni
        </nickname>
        <value>
          119.0
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty>
          7.0
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Co
        </nickname>
        <value>
          45.0
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty>
          3.0
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Fe
        </nickname>
        <value>
          8.63
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.14
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Mn
        </nickname>
        <value>
          1290.0
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty>
          40.0
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Cr
        </nickname>
        <value>
          280.0
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty>
          19.0
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          V
        </nickname>
        <value>
          317.0
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty>
          11.0
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Ti
        </nickname>
        <value>
          1.63
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.02
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Sc
        </nickname>
        <value>
          32.0
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty>
          1.0
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Ca
        </nickname>
        <value>
          8.17
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.12
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          K
        </nickname>
        <value>
          0.43
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.01
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          P
        </nickname>
        <value>
          0.12
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.01
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Si
        </nickname>
        <value>
          23.3
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.3
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Al
        </nickname>
        <value>
          7.16
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.08
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Mg
        </nickname>
        <value>
          4.36
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.07
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Na
        </nickname>
        <value>
          1.64
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.06
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          F
        </nickname>
        <value>
          370.0
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Li
        </nickname>
        <value>
          5.0
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
    </chemistries>
  </acquisition>
  <acquisition>
    <global_id>
      20160823143358-274233
    </global_id>
    <name>
      ref-gl-dr1a1
    </name>
    <device/>
    <technique/>
    <operator/>
    <sample_global_id>
      20090223093036.hkitagawa
    </sample_global_id>
    <sample_name>
      ref-gl-dr1a1
    </sample_name>
    <description/>
    <chemistries>
      <analysis>
        <nickname>
          H2O
        </nickname>
        <value>
          2.29
        </value>
        <unit>
          permil
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Tm
        </nickname>
        <value>
          0.456
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Ho
        </nickname>
        <value>
          1.12
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Nd
        </nickname>
        <value>
          10.2
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Pb
        </nickname>
        <value>
          0.876
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Ta
        </nickname>
        <value>
          0.266
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          U
        </nickname>
        <value>
          0.168
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Th
        </nickname>
        <value>
          0.434
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Rb
        </nickname>
        <value>
          2.13
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Cs
        </nickname>
        <value>
          0.0217
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Lu
        </nickname>
        <value>
          0.456
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Yb
        </nickname>
        <value>
          3.15
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Er
        </nickname>
        <value>
          3.03
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Y
        </nickname>
        <value>
          35.7
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Li
        </nickname>
        <value>
          8.68
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Dy
        </nickname>
        <value>
          5.08
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Tb
        </nickname>
        <value>
          0.794
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Gd
        </nickname>
        <value>
          3.92
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Eu
        </nickname>
        <value>
          1.2
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Hf
        </nickname>
        <value>
          2.48
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Zr
        </nickname>
        <value>
          89.7
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Sm
        </nickname>
        <value>
          3.25
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Sr
        </nickname>
        <value>
          178.0
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Pr
        </nickname>
        <value>
          1.9
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Ce
        </nickname>
        <value>
          12.28
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          La
        </nickname>
        <value>
          4.39
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Nb
        </nickname>
        <value>
          3.71
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Ba
        </nickname>
        <value>
          21.3
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          K2O
        </nickname>
        <value>
          0.34
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.07
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Na2O
        </nickname>
        <value>
          3.33
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.3
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          MgO
        </nickname>
        <value>
          5.83
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.19
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          MnO
        </nickname>
        <value>
          0.39
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          FeO
        </nickname>
        <value>
          7.95
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.62
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Cr2O3
        </nickname>
        <value>
          0.33
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Al2O3
        </nickname>
        <value>
          16.65
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.84
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          TiO2
        </nickname>
        <value>
          1.24
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.16
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          CaO
        </nickname>
        <value>
          10.97
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.39
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          SiO2
        </nickname>
        <value>
          51.33
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.86
        </uncertainty>
        <label/>
        <info/>
      </analysis>
    </chemistries>
  </acquisition>
  <acquisition>
    <global_id>
      20160823143546-072977
    </global_id>
    <name>
      ref-gl-tahiti
    </name>
    <device/>
    <technique/>
    <operator/>
    <sample_global_id>
      20110407093831-292-272
    </sample_global_id>
    <sample_name>
      ref-gl-tahiti
    </sample_name>
    <description/>
    <chemistries>
      <analysis>
        <nickname>
          Tm
        </nickname>
        <value>
          0.797
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Ho
        </nickname>
        <value>
          2.14
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Nd
        </nickname>
        <value>
          111.0
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Pb
        </nickname>
        <value>
          17.4
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Ta
        </nickname>
        <value>
          8.35
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          U
        </nickname>
        <value>
          7.2
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Th
        </nickname>
        <value>
          24.2
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Rb
        </nickname>
        <value>
          154.0
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Cs
        </nickname>
        <value>
          1.34
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Lu
        </nickname>
        <value>
          0.707
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Yb
        </nickname>
        <value>
          4.81
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Er
        </nickname>
        <value>
          5.32
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Y
        </nickname>
        <value>
          62.7
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Li
        </nickname>
        <value>
          20.8
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Dy
        </nickname>
        <value>
          12.2
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Tb
        </nickname>
        <value>
          2.22
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Gd
        </nickname>
        <value>
          15.6
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Eu
        </nickname>
        <value>
          4.7
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Hf
        </nickname>
        <value>
          29.4
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Zr
        </nickname>
        <value>
          1305.0
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Sm
        </nickname>
        <value>
          19.9
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Sr
        </nickname>
        <value>
          107.0
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Pr
        </nickname>
        <value>
          29.1
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Ce
        </nickname>
        <value>
          254.0
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          La
        </nickname>
        <value>
          117.0
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          B
        </nickname>
        <value>
          12.38
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Nb
        </nickname>
        <value>
          150.0
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Ba
        </nickname>
        <value>
          277.0
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          K2O
        </nickname>
        <value>
          6.69
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.37
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Na2O
        </nickname>
        <value>
          6.83
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.36
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          MgO
        </nickname>
        <value>
          0.81
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.11
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          FeO
        </nickname>
        <value>
          4.8
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.18
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Al2O3
        </nickname>
        <value>
          18.31
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.51
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          TiO2
        </nickname>
        <value>
          0.73
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.17
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          CaO
        </nickname>
        <value>
          1.81
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.22
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          SiO2
        </nickname>
        <value>
          58.99
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.91
        </uncertainty>
        <label/>
        <info/>
      </analysis>
    </chemistries>
  </acquisition>
  <acquisition>
    <global_id>
      20160823143634-293742
    </global_id>
    <name>
      ref-pl-bytownite-c
    </name>
    <device/>
    <technique/>
    <operator/>
    <sample_global_id>
      20140424154332-584814
    </sample_global_id>
    <sample_name>
      pl-bytownite-c
    </sample_name>
    <description/>
    <chemistries>
      <analysis>
        <nickname>
          d17O
        </nickname>
        <value>
          3.3155
        </value>
        <unit>
          permil
        </unit>
        <uncertainty>
          0.0065
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          d18O
        </nickname>
        <value>
          6.3155
        </value>
        <unit>
          permil
        </unit>
        <uncertainty>
          0.0055
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          d7Li
        </nickname>
        <value>
          -0.036575
        </value>
        <unit>
          permil
        </unit>
        <uncertainty>
          0.0005
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Be
        </nickname>
        <value>
          0.10878
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty>
          0.009149
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Tm
        </nickname>
        <value>
          0.0019386
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty>
          0.0001306
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Ho
        </nickname>
        <value>
          0.0099178
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty>
          0.0005827
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Nd
        </nickname>
        <value>
          1.144
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty>
          0.02769
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Pb
        </nickname>
        <value>
          0.3398
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty>
          0.01229
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Th
        </nickname>
        <value>
          0.002872
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Rb
        </nickname>
        <value>
          0.3725
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty>
          0.01116
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Lu
        </nickname>
        <value>
          0.00126
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty>
          0.0001522
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Yb
        </nickname>
        <value>
          0.010872
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty>
          0.0006155
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Er
        </nickname>
        <value>
          0.02029
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty>
          0.001371
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Y
        </nickname>
        <value>
          0.25084
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty>
          0.03033
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Li
        </nickname>
        <value>
          7.6402
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty>
          0.5883
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Dy
        </nickname>
        <value>
          0.061804
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty>
          0.002078
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Tb
        </nickname>
        <value>
          0.01355
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty>
          0.0004214
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Gd
        </nickname>
        <value>
          0.13444
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty>
          0.001572
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Eu
        </nickname>
        <value>
          0.4487
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty>
          0.002378
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Sm
        </nickname>
        <value>
          0.17042
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty>
          0.004162
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Sr
        </nickname>
        <value>
          969.6
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty>
          26.85
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Pr
        </nickname>
        <value>
          0.27884
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty>
          0.005615
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Ce
        </nickname>
        <value>
          2.5402
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty>
          0.05794
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          La
        </nickname>
        <value>
          1.393
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty>
          0.05141
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Ba
        </nickname>
        <value>
          126.24
        </value>
        <unit>
          ug/g
        </unit>
        <uncertainty>
          3.071
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          K2O
        </nickname>
        <value>
          0.34
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.13
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Na2O
        </nickname>
        <value>
          4.53
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.37
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          MgO
        </nickname>
        <value>
          0.17
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.14
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          MnO
        </nickname>
        <value>
          0.23
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.17
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          FeO
        </nickname>
        <value>
          0.61
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.31
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Cr2O3
        </nickname>
        <value>
          0.31
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.19
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          Al2O3
        </nickname>
        <value>
          29.04
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.55
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          TiO2
        </nickname>
        <value>
          0.31
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.17
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          CaO
        </nickname>
        <value>
          12.03
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.51
        </uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>
          SiO2
        </nickname>
        <value>
          53.05
        </value>
        <unit>
          cg/g
        </unit>
        <uncertainty>
          0.72
        </uncertainty>
        <label/>
        <info/>
      </analysis>
    </chemistries>
  </acquisition>
</acquisitions>
